// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "paste here";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float airQ;
float hum;
float rain;
float temp;
int soilM;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(airQ, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(hum, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(rain, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(soilM, READ, 5 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
